// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "test.h"

// Forward declaration for C getter
extern int get_latest_temperature(void);
extern lv_obj_t *ui_TemperatureReadings;


// Helper to update the temperature label (can be called from main.cpp)
void update_temperature_label(void)
{
    int temp = get_latest_temperature();
    char buf[16];
    snprintf(buf, sizeof(buf), "%d", temp);
    lv_label_set_text(ui_TemperatureReadings, buf);
    // Also update the Arc value
    extern lv_obj_t *ui_Arc1;
    lv_arc_set_value(ui_Arc1, temp);
}
